### ISSUE TITLE
Getting the following error when calling resetPassword :

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie-plugin-users#38] opened 2015-02-12 16:12 UTC
After setting the smtp configuration in the admin panel I tried to use resetPassword 
and I get HoodieNotFoundError - Error message: Missing

`PUT http://23.253.62.112:6004/_api/_users/org.couchdb.user%3A%24passwordReset%2Fidanb11%40gmail.com%2Fr149x7e 404 (Not Found)`
`jquery.js:8625 n.ajaxTransport.k.cors.a.crossDomain.send`
`jquery.js:8161 n.extend.ajax`
`hoodie.js:7738 17.exports.requesthoodie.js:6341 10.exports.request`
`hoodie.js:6460 (anonymous function)`
`hoodie.js:7171 11.exports.withPreviousRequestsAborted`
`hoodie.js:6459 10.exports.resetPassword`
`hoodie.js:9159 26.angular.module.factory.angular.forEach.service.(anonymous function)`
`controllers.js:59 $scope.hoodieResetPasswordangular.js:10903 gb.functionCall`
`angular.js:19259 jc.(anonymous function).compile.d.on.fangular.js:12811 $get.h.$eval`
`angular.js:12909 $get.h.$apply`
`angular.js:19264 (anonymous function)`
`jquery.js:4430 n.event.dispatch`
`jquery.js:4116 n.event.add.r.handle`

Please help resolving this.

Idanb11

**Comment by idanb11** [comment] 2015-02-14 07:03
Did anybody have any luck using the resetPassword method?

**Comment by janl** [comment] 2015-02-16 13:28
@gr2m can you have a look?

**Comment by janl** [comment] 2015-02-16 13:28
@idanb11 thank you for your report!

**Comment by gr2m** [comment] 2015-02-17 13:30
@idanb11 I'm looking into it. I found the cause of the problem. Hoodie tries internally to subscribe to the passwordreset event once, and uses `state.events.once`, but it should be `state.events.one`. If you have time, you can look into it and get it fixed. If not I'll try to get it fixed tomorrow

**Comment by janl** [comment] 2015-02-17 15:58
@gr2m see https://github.com/hoodiehq/hoodie.js/pull/411

**Comment by gr2m** [comment] 2015-02-17 16:50
@idanb11 fixed via https://github.com/hoodiehq/hoodie.js/pull/411

**Closed by gr2m** 2015-02-17 16:50 UTC
Labels: help wanted, Type: Bug

**Comment by idanb11** [comment] 2015-02-18 07:09
OK great...
How do I update my Hoodie to the latest version?
Because running `$ npm install ` doesn't change the versions...

**Comment by janl** [comment] 2015-02-18 11:27
update the version number(s) in your `package.json`
